### ISSUE TITLE
make functions / types unexported?

### ISSUE THREAD

**Issue by alioguzhan** [sumerc/concurry#1]
There are several warnings in the code. Your functions and variables start with UPPERCASE which means they are `exported` modules. And they require doc comments:

![image](https://user-images.githubusercontent.com/1928541/80042281-3e04f900-8507-11ea-9d16-2c273070803d.png)

https://github.com/golang/go/wiki/CodeReviewComments#doc-comments

To make them `un-exported / private`, we should make them start with a lowercase letter, instead of uppercase.

Or, We should add `doc-comments` for everything which is something needs to be done either way

I didn't see any reason to export those types and functions. Should I open a Pull Request fixes this?

**Comment by sumerc** [comment]
Forgot to install Go linter in my new setup :) 

All fixed with some minor other fixes as well. Please you also check if there are more warnings on your end too and close the issue.

Thanks!

**Comment by alioguzhan** [comment]
Great. Closing the issue...
